version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-project:
    executor: python/default
    steps:
      - checkout 
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python question2/tests/test_swap_by_prefix.py 
          name: Test

workflows:
  main:
    jobs:
      - test-project
